# Install the apt prerequisites
addons:
  apt:
    packages:
      - python-pygments

# Handle git submodules yourself
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - wget https://github.com/spf13/hugo/releases/download/v0.21/hugo_0.21_Linux-64bit.deb
    - sudo dpkg -i hugo_0.21_Linux-64bit.deb
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
# Clean and don't fail
install:
  - rm -rf public || exit 0

# Build the website
script:
  - hugo 

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  target_branch: build
  on:
    branch: master
